development:
  adapter: postgresql
  encoding: unicode
  database: simple_rails_api_development
  pool: 5
  hostname: localhost
  username: postgres
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: simple_rails_api_test
  pool: 5
  hostname: localhost
  username: postgres
  password: 